#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-cachecontrol
Version  : 0.12.10
Release  : 3
URL      : https://files.pythonhosted.org/packages/d0/74/3748ee1144234a525d84c4905002a5f39795d265bcdecca74142a8df5206/CacheControl-0.12.10.tar.gz
Source0  : https://files.pythonhosted.org/packages/d0/74/3748ee1144234a525d84c4905002a5f39795d265bcdecca74142a8df5206/CacheControl-0.12.10.tar.gz
Summary  : httplib2 caching for requests
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-cachecontrol-bin = %{version}-%{release}
Requires: pypi-cachecontrol-python = %{version}-%{release}
Requires: pypi-cachecontrol-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(msgpack)
BuildRequires : pypi(requests)
Provides: CacheControl
Provides: CacheControl-python
Provides: CacheControl-python3

%description
..
SPDX-License-Identifier: Apache-2.0
==============
CacheControl
==============

%package bin
Summary: bin components for the pypi-cachecontrol package.
Group: Binaries

%description bin
bin components for the pypi-cachecontrol package.


%package python
Summary: python components for the pypi-cachecontrol package.
Group: Default
Requires: pypi-cachecontrol-python3 = %{version}-%{release}

%description python
python components for the pypi-cachecontrol package.


%package python3
Summary: python3 components for the pypi-cachecontrol package.
Group: Default
Requires: python3-core
Provides: pypi(cachecontrol)
Requires: pypi(msgpack)
Requires: pypi(requests)

%description python3
python3 components for the pypi-cachecontrol package.


%prep
%setup -q -n CacheControl-0.12.10
cd %{_builddir}/CacheControl-0.12.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641421586
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/doesitcache

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
